[package]
name = "sqlite_web"
version = "0.1.0"
edition = "2021"

[lib]
name = "sqlite_web"
crate-type = ["rlib"]

[dependencies]
sqlite_nostd = { path="../sqlite_nostd"}

[features]
omit_load_extension = ["sqlite_nostd/omit_load_extension"]
